'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,LayoutDashboard,Users,CalendarDays,Settings,History,LogOut,Plus,RefreshCw,Copy,PenLine,QrCode,Menu,X} from 'lucide-react';
import {adminGatewaySchema,type AdminData,type AdminRow} from '@/lib/admin-contracts';
import {clock} from '@/lib/admin-time.mjs';
import {classLevels,toggleClassLevel} from '@/lib/class-levels.mjs';
type Tab='overview'|'students'|'sessions'|'settings'|'audit';
type Editor={kind:'student'|'session'|'settings';row:AdminRow;allLevels?:boolean};
type Field={key:string;label:string;type?:string;optional?:boolean;options?:[string,string][];step?:string;hint?:string};
const statuses:Record<string,string>={present:'มาเรียน',late:'มาสาย',absent:'ขาดเรียน',excused:'ลา',pending:'ยังไม่เช็คชื่อ',active:'กำลังเรียน',inactive:'พ้นสภาพ',draft:'แบบร่าง',open:'เปิดเช็คชื่อ',closed:'ปิดรอบ',cancelled:'ยกเลิก'};
const studentFields:Field[]=[{key:'student_code',label:'รหัสนักศึกษา'},{key:'full_name',label:'ชื่อ–นามสกุล'},{key:'class_level',label:'ระดับชั้น',hint:'เช่น ปวส.1 ใช้ให้ตรงกันกับรอบเรียน'},{key:'group_name',label:'กลุ่ม / ห้อง',optional:true},{key:'enrolled_on',label:'วันที่เริ่มเรียน',type:'date'},{key:'withdrawn_on',label:'วันที่พ้นสภาพ',type:'date',optional:true},{key:'status',label:'สถานะ',options:[['active','กำลังเรียน'],['inactive','พ้นสภาพ']]}];
const locationFields:Field[]=[{key:'room_name',label:'ห้อง / อาคาร'},{key:'latitude',label:'ละติจูด',type:'number',step:'any'},{key:'longitude',label:'ลองจิจูด',type:'number',step:'any'},{key:'radius_m',label:'รัศมีที่เช็คชื่อได้ (เมตร)',type:'number',step:'any'},{key:'max_accuracy_m',label:'ความคลาดเคลื่อนสูงสุด (เมตร)',type:'number',step:'any',hint:'ต้องไม่เกินรัศมีที่อนุญาต'}];
const sessionFields:Field[]=[{key:'session_number',label:'ครั้งที่เรียน',type:'number'},{key:'topic',label:'หัวข้อ',optional:true},{key:'class_level',label:'ระดับชั้น',type:'levels'},{key:'group_name',label:'กลุ่ม / ห้อง',optional:true,hint:'เว้นว่าง = ทุกกลุ่ม'},{key:'starts_at',label:'เริ่มเรียน',type:'datetime-local'},{key:'ends_at',label:'จบเรียน',type:'datetime-local'},{key:'checkin_opens_at',label:'เปิดเช็คชื่อ',type:'datetime-local'},{key:'checkin_closes_at',label:'ปิดเช็คชื่อ',type:'datetime-local'},{key:'late_at',label:'เริ่มนับว่าสาย',type:'datetime-local'},{key:'absence_at',label:'เริ่มนับว่าขาด',type:'datetime-local'},...locationFields,{key:'status',label:'สถานะรอบ',options:[['draft','แบบร่าง'],['open','เปิดเช็คชื่อ'],['closed','ปิดรอบ'],['cancelled','ยกเลิก']]}];
const settingsFields:Field[]=[{key:'course_name',label:'ชื่อวิชา'},{key:'teacher_name',label:'ชื่อผู้สอน'},{key:'term',label:'ภาคเรียน / ปีการศึกษา',optional:true},{key:'location_name',label:'ชื่อสถานศึกษา / สถานที่'},...locationFields,{key:'late_policy',label:'เวลาเข้าสายเริ่มต้น',type:'time'},{key:'absence_policy',label:'เวลาขาดเริ่มต้น',type:'time'}];
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function displayDate(value:string){if(!value)return '—';const d=new Date(value.length===10?value+'T00:00:00+07:00':value+'+07:00');return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',...(value.length>10?{timeStyle:'short' as const}:{}),timeZone:'Asia/Bangkok'}).format(d);}
function shifted(value:string,days:number){const d=new Date(value+'+07:00');d.setUTCDate(d.getUTCDate()+days);return new Date(d.getTime()+7*3600000).toISOString().slice(0,16);}
function Fields({fields,row,onChange,levelPicker}:{fields:Field[];row:AdminRow;onChange:(key:string,value:string)=>void;levelPicker?:React.ReactNode}){return <div className="admin-fields">{fields.map(f=>f.type==='levels'?<div className="admin-level-field" key={f.key}>{levelPicker}</div>:<div key={f.key}><label htmlFor={'field-'+f.key}>{f.label}{f.optional?' (ไม่บังคับ)':''}</label>{f.options?<select id={'field-'+f.key} value={row[f.key]||''} onChange={e=>onChange(f.key,e.target.value)}>{f.options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input id={'field-'+f.key} type={f.type||'text'} step={f.step} required={!f.optional} maxLength={120} value={row[f.key]||''} onChange={e=>onChange(f.key,e.target.value)}/>} {f.hint&&<p className="admin-hint">{f.hint}</p>}</div>)}</div>;}
function SessionLevelPicker({options,selected,all,onAllChange,onToggle}:{options:string[];selected:string[];all:boolean;onAllChange:(value:boolean)=>void;onToggle:(level:string,checked:boolean)=>void}){
 return <fieldset className="admin-level-picker"><legend>ระดับชั้นที่เข้าร่วม</legend><p className="admin-hint">เลือกได้หลายระดับชั้นในรอบเดียว</p><label className="admin-level-option admin-level-all"><input type="checkbox" checked={all} onChange={e=>onAllChange(e.target.checked)}/><span>ทุกระดับชั้น</span></label><div className="admin-level-options">{options.map(level=><label className={'admin-level-option'+(!all&&selected.includes(level)?' selected':'')} key={level}><input type="checkbox" checked={!all&&selected.includes(level)} onChange={e=>onToggle(level,e.target.checked)}/><span>{level}</span></label>)}</div><p className="admin-hint" role="status">{all?'ใช้กับทุกระดับชั้น รวมระดับที่เพิ่มภายหลัง':selected.length?'เลือกแล้ว: '+selected.join(', '):'กรุณาเลือกอย่างน้อย 1 ระดับชั้น หรือเลือกทุกระดับชั้น'}</p></fieldset>;
}
export default function Dashboard({username}:{username:string}){
 const [data,setData]=useState<AdminData|null>(null),[tab,setTab]=useState<Tab>('overview'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[correction,setCorrection]=useState<AdminRow|null>(null),[repeat,setRepeat]=useState(1),[interval,setInterval]=useState(7);
 const flight=useRef(false),loadId=useRef(0);
 const [menuOpen,setMenuOpen]=useState(false);
 const menuButton=useRef<HTMLButtonElement>(null);
 async function load(session=''){
  const id=++loadId.current;setLoading(true);setError('');
  try{const r=await fetch('/api/admin/data'+(session?'?session='+encodeURIComponent(session):''),{cache:'no-store'});if(r.status===401){window.location.assign('/admin/login');return;}const body=adminGatewaySchema.parse(await r.json());if(!r.ok||!body.ok||!body.data)throw new Error(body.message||'โหลดข้อมูลไม่ได้');if(id===loadId.current)setData(body.data);}
  catch(e){if(id===loadId.current)setError(e instanceof Error?e.message:'เชื่อมต่อไม่ได้');}
  finally{if(id===loadId.current)setLoading(false);}
 }
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(editor)document.querySelector('.admin-editor')?.scrollIntoView({block:'start'});},[editor?.kind]);
 useEffect(()=>{if(correction)document.getElementById('attendance-correction')?.scrollIntoView({block:'start'});},[correction?.student_id]);
 async function mutation(action:string,payload:AdminRow){const r=await fetch('/api/admin/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});if(r.status===401){window.location.assign('/admin/login');throw new Error('กรุณาเข้าสู่ระบบอีกครั้ง');}const body=adminGatewaySchema.parse(await r.json());if(!r.ok||!body.ok)throw new Error(body.message||'ยังบันทึกไม่ได้');}
 function edit(kind:Editor['kind'],row:AdminRow){setEditor({kind,row:{...row},allLevels:kind==='session'?!row.class_level?.trim():undefined});setRepeat(1);setError('');setNotice('');setCorrection(null);}
 function newStudent(){edit('student',{student_id:crypto.randomUUID(),student_code:'',full_name:'',class_level:'',group_name:'',status:'active',enrolled_on:today(),withdrawn_on:'',_version:''});}
 function sessionDraft(original?:AdminRow,copy=false){
  if(!data)return;const s=data.settings,day=original?.starts_at.slice(0,10)||today();
  const row:AdminRow={session_id:crypto.randomUUID(),session_number:String(data.sessions.length+1),topic:'',class_level:'',group_name:'',starts_at:day+'T08:00',ends_at:day+'T10:00',checkin_opens_at:day+'T07:45',checkin_closes_at:day+'T10:00',late_at:day+'T'+(clock(s.late_policy)||'08:30'),absence_at:day+'T'+(clock(s.absence_policy)||'09:00'),status:'draft',room_name:s.room_name,latitude:s.latitude,longitude:s.longitude,radius_m:s.radius_m,max_accuracy_m:s.max_accuracy_m,_version:''};
  if(original){for(const f of sessionFields){if(original[f.key])row[f.key]=original[f.key];}row.session_id=copy?crypto.randomUUID():original.session_id;row._version=copy?'':original._version;if(copy){row.status='draft';row.session_number=String(Number(original.session_number||0)+1);for(const key of ['starts_at','ends_at','checkin_opens_at','checkin_closes_at','late_at','absence_at'])row[key]=shifted(row[key],7);}}
  for(const f of sessionFields)if(f.type==='datetime-local')row[f.key]=row[f.key].slice(0,16);
  edit('session',row);
 }
 function editSettings(){if(!data)return;const row:AdminRow={_version:data.settingsVersion};for(const f of settingsFields)row[f.key]=f.type==='time'?clock(data.settings[f.key]||''):data.settings[f.key]||'';edit('settings',row);}
 async function saveEditor(e:React.FormEvent){
  e.preventDefault();if(!editor||flight.current)return;if(editor.kind==='session'&&!editor.allLevels&&!classLevels(editor.row.class_level).length){setError('เลือกอย่างน้อย 1 ระดับชั้น หรือเลือกทุกระดับชั้น');return;}flight.current=true;setBusy(true);setError('');setNotice('');let completed=0;
  const count=editor.kind==='session'&&!editor.row._version?repeat:1;
  try{for(let i=0;i<count;i++){const row={...editor.row};if(editor.kind==='session')row.class_level=editor.allLevels?'':classLevels(row.class_level).join(', ');if(i){row.session_id=crypto.randomUUID();row.session_number=String(Number(row.session_number)+i);for(const key of ['starts_at','ends_at','checkin_opens_at','checkin_closes_at','late_at','absence_at'])row[key]=shifted(row[key],i*interval);}await mutation(editor.kind==='student'?'adminSaveStudent':editor.kind==='session'?'adminSaveSession':'adminSaveSettings',row);completed++;}setEditor(null);setNotice(count>1?`สร้างรอบเรียนแล้ว ${count} รอบ`:'บันทึกเรียบร้อยแล้ว');await load(data?.selectedSessionId);}
  catch(err){const message=err instanceof Error?err.message:'บันทึกไม่ได้';if(completed){setEditor(null);await load(data?.selectedSessionId);}setError((completed?`บันทึกแล้ว ${completed} จาก ${count} รอบ ส่วนที่เหลือยังไม่ได้บันทึก · `:'')+message);}
  finally{flight.current=false;setBusy(false);}
 }
 async function saveCorrection(e:React.FormEvent){e.preventDefault();if(!correction||flight.current)return;flight.current=true;setBusy(true);setError('');try{const {session_id,student_id,status,reason,_version}=correction;await mutation('adminAttendance',{session_id,student_id,status,reason,_version});setCorrection(null);setNotice('แก้ผลเช็คชื่อและบันทึกเหตุผลแล้ว');await load(data?.selectedSessionId);}catch(err){setError(err instanceof Error?err.message:'บันทึกไม่ได้');}finally{flight.current=false;setBusy(false);}}
 async function logout(){if(busy)return;setBusy(true);try{const r=await fetch('/api/admin/logout',{method:'POST'});if(!r.ok)throw new Error();window.location.assign('/admin/login');}catch{setError('ออกจากระบบไม่ได้ กรุณาลองใหม่');setBusy(false);}}
 const current=data?.sessions.find(s=>s.session_id===data.selectedSessionId),byStudent=new Map(data?.attendance.map(r=>[r.student_id,r])),roster=data?.students.filter(s=>data.eligibleStudentIds.includes(s.student_id)||byStudent.has(s.student_id))||[],counts={present:0,late:0,absent:0,excused:0,pending:0};
 for(const s of roster){const key=(byStudent.get(s.student_id)?.status||'pending') as keyof typeof counts;if(key in counts)counts[key]++;}
 const levelOptions=[...new Set(['ปวช.1','ปวช.2','ปวช.3','ปวส.1','ปวส.2',...(data?.students.map(s=>s.class_level.trim())||[]),...(data?.sessions.flatMap(s=>classLevels(s.class_level))||[])].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'th'));
 const tabs:[Tab,string,typeof Users][]=[['overview','ภาพรวมและเช็คชื่อ',LayoutDashboard],['students','นักเรียน',Users],['sessions','รอบเรียน',CalendarDays],['settings','ตั้งค่าวิชา',Settings],['audit','ประวัติการแก้ไข',History]];
 return <div className="admin-shell">
 <header className="admin-navbar" onKeyDown={e=>{if(e.key==='Escape'&&menuOpen){setMenuOpen(false);menuButton.current?.focus();}}}>
  <div className="admin-navbar-inner">
   <div className="admin-nav-top">
    <a href="/" className="admin-brand"><BookOpen/>check name <b>na.</b></a>
    <div className="admin-nav-account"><span>{username}</span><button className="admin-button small" aria-label="ออกจากระบบ" onClick={logout} disabled={busy}><LogOut size={16}/><span className="admin-logout-label">ออกจากระบบ</span></button></div>
    <button ref={menuButton} className="admin-button admin-nav-toggle" type="button" aria-expanded={menuOpen} aria-controls="admin-navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={19}/>:<Menu size={19}/>}เมนู</button>
   </div>
   <div id="admin-navigation" className={'admin-nav-content'+(menuOpen?' is-open':'')}>
    <nav className="admin-nav-links" aria-label="เมนูแอดมิน">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'selected':''} aria-current={tab===key?'page':undefined} disabled={busy} onClick={()=>{setTab(key);setMenuOpen(false);setEditor(null);setCorrection(null);setQuery('');setError('');setNotice('');}}><Icon size={18}/>{label}</button>)}</nav>
    <a className="admin-nav-qr" href="/qr" target="_blank" rel="noreferrer"><QrCode size={18}/>QR สำหรับนักเรียน</a>
   </div>
  </div>
 </header>
 <main className="admin-main"><header className="admin-top"><div><p className="admin-eyebrow">{data?.settings.course_name||'check name na'}</p><h1>{tabs.find(t=>t[0]===tab)?.[1]}</h1><p className="admin-muted">{displayDate(today())} · เวลาไทย</p></div><button className="admin-button" disabled={loading||busy} onClick={()=>{setEditor(null);setCorrection(null);void load(data?.selectedSessionId);}}><RefreshCw size={17}/>{loading?'กำลังโหลด…':'โหลดข้อมูลล่าสุด'}</button></header>
 {error&&<div className="admin-error" role="alert">{error}</div>}{notice&&<div className="admin-success" role="status">{notice}</div>}
 {loading&&!data&&<div className="admin-panel" role="status">กำลังโหลดข้อมูลชั้นเรียน…</div>}
 {data&&<>
 {editor&&<section className="admin-panel admin-editor"><div className="admin-section-heading"><div><p className="admin-eyebrow">{editor.row._version?'แก้ไขข้อมูล':'เพิ่มข้อมูลใหม่'}</p><h2>{editor.kind==='student'?'ข้อมูลนักเรียน':editor.kind==='session'?'รอบเรียน':'การตั้งค่าวิชา'}</h2></div><button className="admin-button" aria-label="ปิดแบบฟอร์ม" disabled={busy} onClick={()=>setEditor(null)}><X size={18}/></button></div>{editor.kind==='session'&&<p className="admin-muted">วันเวลาทั้งหมดเป็นเวลาไทย รอบใหม่เป็นแบบร่าง เลือก “เปิดเช็คชื่อ” เมื่อตรวจข้อมูลครบแล้ว</p>}{editor.kind==='settings'&&<p className="admin-muted">ใช้เป็นค่าเริ่มต้นของรอบใหม่ และรอบเก่าที่ไม่ได้กำหนดแยกไว้</p>}<form onSubmit={saveEditor}><fieldset disabled={busy}><Fields fields={editor.kind==='student'?studentFields:editor.kind==='session'?sessionFields:settingsFields} row={editor.row} levelPicker={<SessionLevelPicker options={levelOptions} selected={classLevels(editor.row.class_level)} all={!!editor.allLevels} onAllChange={allLevels=>setEditor({...editor,allLevels})} onToggle={(level,checked)=>setEditor({...editor,allLevels:false,row:{...editor.row,class_level:toggleClassLevel(editor.allLevels?'':editor.row.class_level,level,checked)}})}/>} onChange={(key,value)=>setEditor({...editor,row:{...editor.row,[key]:value}})}/>{editor.kind==='session'&&!editor.row._version&&<div className="admin-repeat"><label>จำนวนรอบล่วงหน้า<input type="number" min={1} max={12} required value={repeat} onChange={e=>setRepeat(Math.min(12,Math.max(1,Number(e.target.value))))}/></label><label>เว้นระยะ<select value={interval} onChange={e=>setInterval(Number(e.target.value))}><option value={7}>ทุกสัปดาห์</option><option value={1}>ทุกวัน</option></select></label></div>}<div className="admin-actions"><button className="admin-button primary" disabled={busy}>{busy?'กำลังบันทึก…':repeat>1&&editor.kind==='session'?`สร้าง ${repeat} รอบ`:'บันทึกข้อมูล'}</button><button type="button" className="admin-button" onClick={()=>setEditor(null)}>ยกเลิก</button></div></fieldset></form></section>}
 {tab==='overview'&&<><section className="admin-panel"><label htmlFor="session-picker">เลือกรอบเรียน</label><select id="session-picker" value={data.selectedSessionId} disabled={busy||loading} onChange={e=>{setCorrection(null);void load(e.target.value);}}>{!data.sessions.length&&<option value="">ยังไม่มีรอบเรียน</option>}{data.sessions.map(s=><option key={s.session_id} value={s.session_id}>{displayDate(s.starts_at)} · {s.topic||'รอบที่ '+s.session_number} · {s.class_level||'ทุกระดับ'} {s.group_name}</option>)}</select>{current&&<p className="admin-hint">{statuses[current.status]} · {current.room_name||data.settings.room_name} · ผู้เรียนในรอบนี้ {roster.length} คน</p>}</section><div className="admin-stats">{Object.entries(counts).map(([key,count])=><div className={'admin-stat '+key} key={key}><span>{statuses[key]}</span><strong>{count}</strong></div>)}</div>
 {correction&&<section id="attendance-correction" className="admin-panel"><h2>แก้ผล: {correction.name}</h2><form onSubmit={saveCorrection}><fieldset disabled={busy}><label htmlFor="correction-status">ผลเช็คชื่อ</label><select id="correction-status" value={correction.status} onChange={e=>setCorrection({...correction,status:e.target.value})}>{['present','late','absent','excused'].map(s=><option key={s} value={s}>{statuses[s]}</option>)}</select><label htmlFor="correction-reason">เหตุผล (บังคับ)</label><textarea id="correction-reason" required maxLength={500} value={correction.reason} onChange={e=>setCorrection({...correction,reason:e.target.value})}/><div className="admin-actions"><button className="admin-button primary">{busy?'กำลังบันทึก…':'บันทึกการแก้ไข'}</button><button className="admin-button" type="button" onClick={()=>setCorrection(null)}>ยกเลิก</button></div></fieldset></form></section>}
 <section className="admin-panel"><div className="admin-section-heading"><h2>ผลเช็คชื่อรายคน</h2><span className="admin-muted">{roster.length} คน</span></div><input aria-label="ค้นหาผลเช็คชื่อ" placeholder="ค้นหาชื่อหรือรหัสนักศึกษา" value={query} onChange={e=>setQuery(e.target.value)}/><div className="admin-table-wrap"><table><thead><tr><th>ผู้เรียน</th><th>ระดับ / กลุ่ม</th><th>ผลเช็คชื่อ</th><th>เวลาที่เช็คจริง</th><th>จัดการ</th></tr></thead><tbody>{roster.filter(s=>(s.full_name+' '+s.student_code).toLowerCase().includes(query.toLowerCase())).map(s=>{const a=byStudent.get(s.student_id);return <tr key={s.student_id}><td><strong>{s.full_name}</strong><small>{s.student_code}</small></td><td>{s.class_level}<small>{s.group_name}</small></td><td><span className={'admin-badge '+(a?.status||'pending')}>{statuses[a?.status||'pending']}</span>{a?.method==='teacher'&&<small>อาจารย์แก้ไข</small>}</td><td>{displayDate(a?.checked_at||'')}</td><td><button className="admin-button small" disabled={busy||loading} onClick={()=>{setError('');setNotice('');setCorrection({session_id:data.selectedSessionId,student_id:s.student_id,name:s.full_name,status:a?.status||'present',reason:'',_version:a?._version||''});}}><PenLine size={15}/>แก้ผล</button></td></tr>;})}</tbody></table></div>{!roster.length&&<p className="admin-empty">ยังไม่มีผู้เรียนในรอบนี้ เพิ่มรายชื่อและตรวจระดับชั้น/กลุ่มให้ตรงกับรอบเรียน</p>}<p className="admin-hint">“ยังไม่เช็คชื่อ” หมายถึงยังไม่มีรายการบันทึก ระบบตัดขาดอัตโนมัติจะทำงานตามรอบของตัวตั้งเวลา</p></section></>}
 {tab==='students'&&<section className="admin-panel"><div className="admin-section-heading"><h2>รายชื่อนักเรียน <span>{data.students.length}</span></h2><button className="admin-button primary" onClick={newStudent} disabled={busy}><Plus size={18}/>เพิ่มนักเรียน</button></div><input aria-label="ค้นหานักเรียน" placeholder="ค้นหาชื่อ รหัส ระดับชั้น หรือกลุ่ม" value={query} onChange={e=>setQuery(e.target.value)}/><div className="admin-table-wrap"><table><thead><tr><th>ผู้เรียน</th><th>ระดับชั้น</th><th>กลุ่ม</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{data.students.filter(s=>(s.full_name+' '+s.student_code+' '+s.class_level+' '+s.group_name).toLowerCase().includes(query.toLowerCase())).map(s=><tr key={s.student_id}><td><strong>{s.full_name}</strong><small>{s.student_code}</small></td><td>{s.class_level}</td><td>{s.group_name||'—'}</td><td><span className={'admin-badge '+s.status}>{statuses[s.status]}</span></td><td><button className="admin-button small" disabled={busy} onClick={()=>{const row:AdminRow={student_id:s.student_id,_version:s._version};for(const f of studentFields)row[f.key]=s[f.key]||'';edit('student',row);}}><PenLine size={15}/>แก้ไข</button></td></tr>)}</tbody></table></div>{!data.students.length&&<p className="admin-empty">เริ่มต้นด้วยการเพิ่มนักเรียนคนแรก</p>}</section>}
 {tab==='sessions'&&<section className="admin-panel"><div className="admin-section-heading"><h2>รอบเรียนทั้งหมด</h2><button className="admin-button primary" onClick={()=>sessionDraft()} disabled={busy}><Plus size={18}/>เพิ่มรอบเรียน</button></div><p className="admin-muted">แต่ละรอบกำหนดเวลาและสถานที่ได้เอง คัดลอกรอบเดิมไปสัปดาห์หน้าได้</p><div className="admin-session-list">{data.sessions.map(s=><article key={s.session_id}><div><span className={'admin-badge '+s.status}>{statuses[s.status]}</span><h3>{s.topic||'รอบที่ '+s.session_number}</h3><p>{displayDate(s.starts_at)} – {clock(s.ends_at)}</p><p className="admin-muted">{s.class_level||'ทุกระดับชั้น'} · {s.group_name||'ทุกกลุ่ม'} · {s.room_name||data.settings.room_name}</p><small>สาย {clock(s.late_at)||clock(data.settings.late_policy)} · ขาด {clock(s.absence_at)||clock(data.settings.absence_policy)}</small></div><div className="admin-actions"><button className="admin-button small" disabled={busy} onClick={()=>sessionDraft(s)}><PenLine size={15}/>แก้ไข</button><button className="admin-button small" disabled={busy} onClick={()=>sessionDraft(s,true)}><Copy size={15}/>คัดลอก</button></div></article>)}</div>{!data.sessions.length&&<p className="admin-empty">ยังไม่มีรอบเรียน กด “เพิ่มรอบเรียน” เพื่อเริ่มต้น</p>}</section>}
 {tab==='settings'&&!editor&&<section className="admin-panel"><div className="admin-section-heading"><h2>ข้อมูลวิชาและค่าเริ่มต้น</h2><button className="admin-button primary" onClick={editSettings}><PenLine size={17}/>แก้ไข</button></div><dl className="admin-settings">{settingsFields.map(f=><div key={f.key}><dt>{f.label}</dt><dd>{data.settings[f.key]||'—'}</dd></div>)}</dl><p className="admin-hint">การเปลี่ยนค่าเริ่มต้นจะไม่เปลี่ยนรอบที่บันทึกเวลาและสถานที่แยกไว้แล้ว</p></section>}
 {tab==='audit'&&<section className="admin-panel"><h2>การแก้ไขล่าสุด 50 รายการ</h2><p className="admin-muted">บัญชีนี้ใช้ร่วมกัน ประวัติจะระบุชื่อบัญชีแอดมินเดียวกันทุกครั้ง</p><div className="admin-audit">{data.audit.map(a=><details key={a.audit_id}><summary><span><strong>{{Students:'ข้อมูลนักเรียน',Sessions:'รอบเรียน',Attendance:'ผลเช็คชื่อ',Settings:'ตั้งค่าวิชา'}[a.entity_type]||a.entity_type}</strong><small>{displayDate(a.occurred_at)} · {a.actor_id}</small></span><span>{a.action==='create'?'เพิ่มข้อมูล':'แก้ไข'}</span></summary>{a.reason&&<p>เหตุผล: {a.reason}</p>}<p className="admin-hint">รหัสรายการ: {a.entity_id}</p><h3>ก่อนแก้ไข</h3><pre>{a.before_json}</pre><h3>หลังแก้ไข</h3><pre>{a.after_json}</pre></details>)}</div>{!data.audit.length&&<p className="admin-empty">ยังไม่มีประวัติการแก้ไขผ่านหน้าแอดมิน</p>}</section>}
 </>}
 </main></div>;
}
