import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const out=fileURLToPath(new URL('../spreadsheet/',import.meta.url));
const wb=Workbook.create();
const schema={
Settings:['key|text|รหัสการตั้งค่า ห้ามซ้ำ','value|text|ค่าการตั้งค่า','description|text|คำอธิบาย'],
Students:['student_id|id|รหัสผู้เรียนถาวร ห้ามซ้ำ ไม่ใช้เลขแถว','student_code|text|รหัสนักเรียน/นักศึกษา ห้ามซ้ำ เก็บเลขศูนย์นำหน้า','full_name|text|ชื่อและนามสกุล','group_name|text|ห้องหรือกลุ่มเรียน เว้นว่างได้หากมีหนึ่งกลุ่ม','status|enum|active / inactive','enrolled_on|date|วันที่เริ่มเรียนวิชานี้','withdrawn_on|date|วันที่พ้นสภาพในวิชานี้ เว้นว่างได้'],
Sessions:['session_id|id|รหัสรอบเรียน ห้ามซ้ำ แม้มีหลายรอบในวันเดียวกัน','session_number|integer|ครั้งที่เรียน เช่น 1, 2, 3','topic|text|หัวข้อที่เรียน เว้นว่างได้','group_name|text|กลุ่มที่เรียนรอบนี้ ว่างหมายถึงทุกกลุ่ม','starts_at|datetime|วันเวลาเริ่มเรียน เวลาไทย','ends_at|datetime|วันเวลาจบเรียน ต้องหลังเวลาเริ่ม','checkin_opens_at|datetime|วันเวลาเปิดเช็คชื่อ หากให้ผู้เรียนเช็คเอง','checkin_closes_at|datetime|วันเวลาปิดเช็คชื่อ หากให้ผู้เรียนเช็คเอง','late_after_at|datetime|หลังเวลานี้ถือว่าสาย กำหนดตามนโยบายครู','status|enum|draft / open / closed / cancelled'],
Attendance:['attendance_id|id|รหัสรายการ ห้ามซ้ำ','session_id|id|อ้างอิง Sessions หนึ่งคู่ session_id กับ student_id มีหนึ่งรายการ','student_id|id|อ้างอิง Students ต้องตรวจกลุ่มและช่วงวันที่มีสิทธิ์เรียน','status|enum|present / late / absent / excused','checked_at|datetime|เวลาที่เช็คจริงจากเซิร์ฟเวอร์ ขาด/ลาอาจไม่มีค่า','method|enum|teacher / self / qr','recorded_by|text|รหัสผู้ใช้ที่ยืนยันตัวตนแล้ว ระบบระบุเอง','request_id|id|ใช้รหัสเดิมเมื่อส่งคำขอซ้ำ เซิร์ฟเวอร์ต้องกันข้อมูลซ้ำ','note|text|หมายเหตุหรือเหตุผลการลา เก็บเฉพาะที่จำเป็น','created_at|datetime|เวลาสร้างรายการโดยเซิร์ฟเวอร์','updated_at|datetime|เวลาแก้ไขล่าสุดโดยเซิร์ฟเวอร์'],
AuditLog:['audit_id|id|รหัสประวัติ ห้ามซ้ำ','occurred_at|datetime|เวลาดำเนินการ','actor_id|text|รหัสผู้ใช้ที่ยืนยันตัวตนแล้ว','action|enum|create / update / correct / close_session / cancel_session','entity_type|text|Students / Sessions / Attendance / Settings','entity_id|id|รหัสรายการที่ได้รับผล','before_json|text|ค่าก่อนแก้ เฉพาะช่องที่เปลี่ยน ไม่เก็บความลับ','after_json|text|ค่าหลังแก้ เฉพาะช่องที่เปลี่ยน','reason|text|เหตุผลการแก้ผลเช็คชื่อ']
};
const names=['StartHere',...Object.keys(schema),'Dictionary'];
schema.Students.push('class_level|text|ระดับชั้น ต้องตรงกับรายการที่ให้เลือกบนเว็บ');
schema.Sessions=schema.Sessions.filter(x=>!x.startsWith('late_after_at|'));
schema.Sessions.push('class_level|text|ระดับชั้นที่เรียนรอบนี้ เว้นว่างหมายถึงทุกระดับ');
schema.Attendance=schema.Attendance.map(x=>x.startsWith('method|')?'method|enum|teacher / self / qr / system':x.startsWith('recorded_by|')?'recorded_by|text|self-reported เมื่อผู้เรียนกรอกชื่อหรือรหัสเอง ไม่ใช่บัญชียืนยันตัวตน':x);
schema.Attendance.push('class_level|text|ระดับชั้น ณ เวลาเช็คชื่อ','latitude|number|ละติจูดจากอุปกรณ์','longitude|number|ลองจิจูดจากอุปกรณ์','accuracy_m|number|ความคลาดเคลื่อนพิกัด หน่วยเมตร','distance_m|number|ระยะห่างจากจุดห้องเรียนที่เซิร์ฟเวอร์คำนวณ หน่วยเมตร','location_status|enum|inside / not_checked');
for(const n of names)wb.worksheets.add(n);
function style(sh,rows,cols){sh.showGridLines=false;const r=sh.getRangeByIndexes(0,0,rows,cols);r.format.font={name:'Arial',size:11,color:'#152A43'};r.format.rowHeight=26;r.format.columnWidth=25;r.format.verticalAlignment='center';sh.getRangeByIndexes(0,0,1,cols).format={fill:'#17365D',font:{name:'Arial',size:11,bold:true,color:'#FFFFFF'},rowHeight:42,wrapText:true,horizontalAlignment:'center'};sh.freezePanes.freezeRows(1);}
const dictionary=[['sheet','field','type','description_th']];
for(const [name,fields] of Object.entries(schema)){
 const sh=wb.worksheets.getItem(name), reserve=['Students','Attendance'].includes(name)?301:31, defs=fields.map(x=>x.split('|'));
 sh.getRangeByIndexes(0,0,1,fields.length).values=[defs.map(x=>x[0])];style(sh,reserve,fields.length);
 defs.forEach(([field,type,desc],i)=>{dictionary.push([name,field,type,desc]);const r=sh.getRangeByIndexes(1,i,reserve-1,1);if(['text','id','enum'].includes(type))r.setNumberFormat('@');if(type==='date')r.setNumberFormat('yyyy-mm-dd');if(type==='datetime')r.setNumberFormat('yyyy-mm-dd hh:mm:ss');if(type==='integer')r.setNumberFormat('0');if(type==='enum')r.dataValidation={rule:{type:'list',values:desc.split(' / ')}};});
 if(name!=='Settings')sh.getRange(`A2:A${reserve}`).conditionalFormats.addCustom(`AND(A2<>"",COUNTIF($A$2:$A$${reserve},A2)>1)`,{fill:'#FEE2E2',font:{color:'#991B1B'}});
}
const st=wb.worksheets.getItem('Students');st.getRange('C1:C301').format.columnWidth=36;st.getRange('B2:B301').conditionalFormats.addCustom('AND(B2<>"",COUNTIF($B$2:$B$301,B2)>1)',{fill:'#FEE2E2',font:{color:'#991B1B'}});
wb.worksheets.getItem('Attendance').getRange('B2:C301').conditionalFormats.addCustom('AND($B2<>"",$C2<>"",COUNTIFS($B$2:$B$301,$B2,$C$2:$C$301,$C2)>1)',{fill:'#FEE2E2',font:{color:'#991B1B'}});
const settings=[['app_name','check name na','ชื่อเว็บ'],['schema_version','class-v2','เช็คชื่อด้วย QR และตรวจพิกัด'],['course_name','','กรอกชื่อวิชา'],['teacher_name','อาจารย์ปภังกร บุตรศรี','ผู้สอน'],['term','','ภาคเรียนและปีการศึกษา'],['timezone','Asia/Bangkok','ตั้งเขตเวลาของ Google Sheets ให้ตรงกันด้วย'],['attendance_mode','qr','QR เปิดหน้าเว็บ ผู้เรียนกรอกชื่อหรือรหัสและเลือกระดับชั้น'],['late_policy','ตั้งแต่ 08:30','กฎในเซิร์ฟเวอร์ เวลาไทย'],['absence_policy','ตั้งแต่ 09:00','กฎในเซิร์ฟเวอร์ เวลาไทย'],['setup_status','draft','รอเชื่อมชีต กำหนดพิกัดและทดสอบ'],['location_name','วิทยาลัยการอาชีพเถิน จ.ลำปาง','สถานที่ตามที่ผู้ใช้กำหนด'],['room_name','','ชื่ออาคารและห้องเรียนจริง'],['latitude','','ละติจูดจุดกึ่งกลางพื้นที่เช็คชื่อ'],['longitude','','ลองจิจูดจุดกึ่งกลางพื้นที่เช็คชื่อ'],['radius_m','','รัศมีอนุญาต หน่วยเมตร มากกว่า 0'],['max_accuracy_m','','ความคลาดเคลื่อน GPS สูงสุด ไม่เกินรัศมี']];
const s=wb.worksheets.getItem('Settings');s.getRange(`A2:C${settings.length+1}`).values=settings;s.getRange('A1:A31').format.columnWidth=28;s.getRange('B1:B31').format.columnWidth=40;s.getRange('C1:C31').format.columnWidth=78;settings.forEach((row,i)=>{if(!row[1])s.getRange(`B${i+2}`).format.fill='#FFF1CC';});
const guide=[['หัวข้อ','รายละเอียด'],['check name na','ระบบเช็คชื่อเข้าเรียนวิชาเดียว ผู้เรียนประมาณ 300 คน'],['สถานะ','โครงสร้างเปล่า ไม่มีข้อมูลผู้เรียนจริง ยังไม่ได้เชื่อมเว็บหรือ Google Sheets'],['เริ่มต้น 1','กรอกชื่อวิชา ผู้สอน และภาคเรียนในช่องสีเหลืองของ Settings'],['เริ่มต้น 2','กรอกรายชื่อใน Students เตรียม 300 แถว เพิ่มต่อได้โดยไม่ต้องสร้างแท็บใหม่'],['เริ่มต้น 3','สร้างหนึ่งแถวใน Sessions ต่อการเรียนหนึ่งครั้ง วันเดียวกันมีหลายรอบได้'],['เริ่มต้น 4','Attendance เก็บหนึ่งแถวต่อผู้เรียนหนึ่งคนต่อรอบเรียน ไม่มีการเช็คเข้า-ออกงาน'],['สถานะเช็คชื่อ','present = มา, late = สาย, absent = ขาด, excused = ลาที่อนุมัติแล้ว'],['ยังไม่ได้เช็ค','ไม่มีรายการหมายถึงยังไม่ได้เช็ค ไม่ถือว่าขาดโดยอัตโนมัติ'],['กลุ่มเรียน','หากวิชาเดียวมีหลายห้อง ใช้ group_name ใน Students และ Sessions ให้ตรงกัน'],['การขาดเรียน','สรุปหลังปิดรอบและตรวจรายชื่อที่มีสิทธิ์เรียน ไม่รวมผู้ถอนหรือรอบที่ยกเลิก'],['วิธีเช็คชื่อ','รองรับโครงสร้างครูเช็ค ผู้เรียนเช็คเอง หรือ QR ยังไม่ได้เลือกหรือสร้างวิธีใด'],['เวลาและการมาสาย','ใช้เวลาจากเซิร์ฟเวอร์สำหรับการเช็คเอง กำหนดเกณฑ์สายตามครู ไม่เดาค่าเริ่มต้น'],['การแก้ไขย้อนหลัง','ปรับรายการเดิม และบันทึกผู้แก้ ค่าเดิม ค่าใหม่ พร้อมเหตุผลใน AuditLog'],['สิทธิ์แก้ผล','เว็บต้องตรวจสิทธิ์ครู ผู้เรียนต้องแก้ผลหรืออนุมัติการลาของตนเองไม่ได้'],['ข้อมูลไม่ซ้ำ','หนึ่งคู่ session_id + student_id มีหนึ่งรายการ บังคับที่เซิร์ฟเวอร์ด้วยล็อกหรือคิว'],['ชื่อช่อง','คงชื่อแท็บและหัวคอลัมน์แถว 1 เริ่มข้อมูลแถว 2 ดูคำอธิบายใน Dictionary'],['รหัสผู้เรียน','ใช้รหัสถาวร ไม่ใช้เลขแถว เก็บ student_code เป็นข้อความเพื่อรักษาเลขศูนย์นำหน้า'],['การเพิ่มแถว','ขยายรูปแบบและ validation ตามข้อมูลใหม่ ไม่จำกัดจำนวนไว้ที่ 300 แถว'],['สิทธิ์เข้าถึงชีต','ให้สิทธิ์เจ้าของและผู้สอนที่เกี่ยวข้อง ไม่เปิดข้อมูลผู้เรียนเป็นสาธารณะ'],['ขนาดข้อมูล','ตัวอย่าง 300 คน × 40 รอบ = 12,000 รายการต่อภาคเรียน ไม่ใช่ข้อมูลจริง'],['ก่อนใช้งานจริง','ต้องเชื่อมเว็บ ทดสอบสิทธิ์ คำขอซ้ำ และช่วงที่หลายคนเช็คชื่อพร้อมกัน'],['สรุปผล','รอบนี้เตรียมฐานข้อมูล ยังไม่มีสูตรสรุป คะแนน หรือเกณฑ์ผ่านการเข้าเรียน'],['Google Sheets','นำเข้าไฟล์นี้แล้วตั้งเขตเวลา Asia/Bangkok และตรวจรายการเลือกหลังแปลงไฟล์']];
const updates={'เริ่มต้น 1':'กรอกชื่อวิชา ภาคเรียน ชื่อห้อง พิกัด รัศมี และความคลาดเคลื่อนที่ยอมรับใน Settings','เริ่มต้น 2':'กรอกรายชื่อ รหัส และ class_level ใน Students ระบบสร้างรายการระดับชั้นจากข้อมูลจริง','เริ่มต้น 3':'Sessions ต้องมีวันเวลาเริ่ม/จบ เปิด/ปิดเช็คชื่อ และตั้ง status เป็น open เมื่อพร้อม','ยังไม่ได้เช็ค':'หลัง 09:00 ฟังก์ชัน finalizeAbsences จะเพิ่มขาดให้รายชื่อที่ยังไม่เช็ค ต้องติดตั้ง trigger','วิธีเช็คชื่อ':'สแกน QR เปิดเว็บ กรอกชื่อหรือรหัส เลือกระดับชั้น และอนุญาตตำแหน่ง','เวลาและการมาสาย':'ก่อน 08:30 มาเรียน ตั้งแต่ 08:30 สาย ตั้งแต่ 09:00 ขาด ใช้เวลาเซิร์ฟเวอร์ไทย','การขาดเรียน':'trigger ทำงานทุก 5 นาที หลัง 09:00 เฉพาะรอบของวันนี้และผู้เรียนที่มีสิทธิ์ ไม่ทับผลเดิม','สิทธิ์แก้ผล':'หน้าผู้เรียนไม่มีสิทธิ์แก้ผล ครูแก้ในชีตที่จำกัดสิทธิ์ พร้อมบันทึกเหตุผลใน AuditLog'};
guide.forEach(r=>{if(updates[r[0]])r[1]=updates[r[0]];});
guide.push(['ตรวจพิกัด','ต้องอยู่ในรัศมี และระยะห่าง + ความคลาดเคลื่อนต้องไม่เกินรัศมี ไม่ยืนยันตำแหน่งถึงระดับห้อง/ชั้น'],['ชื่อหรือรหัส','เป็นการเทียบรายชื่อ ไม่ใช่การพิสูจน์ตัวตนแบบรหัสผ่าน และ QR แบบลิงก์ส่งต่อกันได้'],['แหล่งอ้างอิงพิกัด','https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates/accuracy']);
const g=wb.worksheets.getItem('StartHere');g.getRange(`A1:B${guide.length}`).values=guide;style(g,guide.length,2);g.getRange(`A1:A${guide.length}`).format.columnWidth=29;g.getRange(`B1:B${guide.length}`).format.columnWidth=112;g.getRange(`A2:B${guide.length}`).format.rowHeight=35;g.getRange(`B2:B${guide.length}`).format.wrapText=true;g.tabColor='#17365D';
const d=wb.worksheets.getItem('Dictionary');d.getRange(`A1:D${dictionary.length}`).values=dictionary;style(d,dictionary.length,4);d.getRange(`B1:B${dictionary.length}`).format.columnWidth=29;d.getRange(`C1:C${dictionary.length}`).format.columnWidth=15;d.getRange(`D1:D${dictionary.length}`).format.columnWidth=103;d.tabColor='#8193A7';
wb.recalculate();
console.log((await wb.inspect({kind:'sheet',include:'id,name',maxChars:1500})).ndjson);
console.log((await wb.inspect({kind:'table',range:'Settings!A1:C11',include:'values,formulas',tableMaxRows:11,tableMaxCols:3,maxChars:1800})).ndjson);
console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?',options:{useRegex:true,maxResults:10},summary:'error scan',maxChars:500})).ndjson);
await fs.mkdir(out,{recursive:true});
for(const name of names){const last=name==='StartHere'?'B':name==='Dictionary'?'D':String.fromCharCode(64+schema[name].length),end=name==='StartHere'?guide.length:name==='Dictionary'?10:name==='Settings'?settings.length+1:5;const img=await wb.render({sheetName:name,range:`A1:${last}${end}`,scale:1,format:'png'});await fs.writeFile(`${out}/preview-${name}.png`,new Uint8Array(await img.arrayBuffer()));}
await fs.writeFile(`${out}/schema.json`,JSON.stringify(schema,null,2));
const xlsx=await SpreadsheetFile.exportXlsx(wb);await xlsx.save(`${out}/check-name-na-structure.xlsx`);console.log('EXPORTED class attendance structure: 7 sheets');
